### ISSUE TITLE
Wont run on Python2.7.12

### ISSUE THREAD

**Issue by amrx101** [paulgb/notify.run#1]
Following required package not found.

```bash
(sample) local:~ amit$ notify-run register
Traceback (most recent call last):
  File "/Users/amit/.virtualenvs/sample/bin/notify-run", line 7, in <module>
    from notify_run.cli import main
  File "/Users/amit/.virtualenvs/sample/lib/python2.7/site-packages/notify_run/__init__.py", line 4, in <module>
    from urllib.parse import urlparse
ImportError: No module named parse

```

There doesn't seem to be a requirements.txt file. Here are the packages installed when notify-run is pip installed.

``` bash

certifi (2018.1.18)
chardet (3.0.4)
idna (2.6)
notify-run (0.0.5)
pip (9.0.3)
PyQRCode (1.2.1)
requests (2.18.4)
setuptools (39.0.1)
urllib3 (1.22)
wheel (0.30.0)

```

**Comment by paulgb** [comment]
Thanks for reporting; I realized I'd never gotten around to testing on Python 2.7. The most recent update (0.0.8) should solve it, if not feel free to re-open this issue.

I've also set up Travis CI with Python 2.7 to prevent this from happening again. I don't have tests so it won't catch usage differences between the versions, but it will catch import errors.
