### ISSUE TITLE
specify the channel in the Python code

### ISSUE THREAD

**Issue by jabbalaci** [paulgb/notify.run#15]
I find it a bit strange that I don't need to specify the channel where I want to send the message to:

    from notify_run import Notify
    notify = Notify()
    notify.send('sent from my Python script')

I prefer the way in the curl example: 

    curl https://notify.run/<channel_id> -d "message goes here"

Can we specify the channel ID in Python too? Thanks.

**Comment by paulgb** [comment]
The channel can be specified when you conatruct the `Notify` object, i.e. `Notify(endpoint="https://notify.run/<channel_id>")`, but I agree that it is a confusing interface for the use case where you don't want to use the library's channel configuration file. I'm not opposed to adding a functional API for sending messages to a specified endpoint.

**Comment by jabbalaci** [comment]
If we can specify it when constructing the Notify object, then it's good for me. Thanks for the answer and thanks for the great project! Please add your previous example to the README.

**Comment by MattArceri** [comment]
This seems to be an issue again. In my testing and from my reading of the codebase, endpoint is completely ignored on initialization. It's an intended argument but instead of reading the arg into a class variable and using the default arg of none, it's explicitly initialization to none no matter what. See the following snippet:
`class Notify:
    def __init__(self, api_server=None, endpoint=None):
        self.api_server = api_server or DEFAULT_API_SERVER
        self.endpoint = None
        self._config_file = expanduser(CONFIG_FILENAME)`

**Comment by paulgb** [comment]
Good suggestion, done.
