### ISSUE TITLE
Render html in notify messages?

### ISSUE THREAD

**Issue by Tehsurfer** [paulgb/notify.run#24]
Is there any way to render html in a notify message? 

I'd like to create a link that can be clicked from the notification or server location. 

EG.
```HTML
<a href="https://www.google.co.nz/">Available Here</a>
```

**Comment by paulgb** [comment]
Hi Jesse,

It does not support general HTML (which is a limitation of the Web
Notification API), but you can specify a URL to go to when the notification
is clicked with the "action" parameter of send()

https://github.com/notify-run/notify.run/blob/3c0a148657266ff328d530fb4be3f88ece344aa9/py_client/notify_run/__init__.py#L108

-- Paul

**Comment by Tehsurfer** [comment]
> but you can specify a URL to go to when the notification is clicked with the "action" parameter of send()

Wow thanks for your help Paul that is even better! I completely missed this in the docs, I'll read a bit deeper next time. 

Awesome project by the way! Thank you for sharing.

**Comment by paulgb** [comment]
No problem, it's possible I overlooked that when writing the docs (if I remember it was a later addition). Glad it helps!
