### ISSUE TITLE
Failsafe notify.send

### ISSUE THREAD

**Issue by Svhorsch** [paulgb/notify.run#30]
Hey there,

maybe im using it slightly wrong, but here the situation:
im training some neuronal networks for my master thesis and to be up to date if everything works, im using notify during training. 
so maybe my usecase is off focus, but training these networks take quite some time (~1 week) and i didnt had any possibility to recontinue after something failed. and now after one day of training, the notify.send throw an error because of a network problem (dk where it happend, on my server or on the notify server). 
i would really appreciate to add to the documentation that this call might fail with an exception or add the possibility to make it fail silently (since IMHO a logging should never cause an application to die)

greeting,
Georg

**Comment by paulgb** [comment]
Hi Georg,

I’m very sorry that happened to you. I agree that logging should never
crash the program; I thought that was already the case with notify.run but
I see now that it is not. I will fix this ASAP.

— Paul

**Comment by paulgb** [comment]
`notify.send()` is now failsafe in notify-run 0.0.14.
