### ISSUE TITLE
Notifications not working on phone

### ISSUE THREAD

**Issue by Contro28** [paulgb/notify.run#35]
Sorry for my English (I use a translator) and for the request in the wrong place, but I really don't know where or who to ask.

Notifications not working on my phone (xiaomi note 7).
I'm going crazy, they worked before and now they don't.
notify.run in Kiwibrowser work but I don't get the notification (no popup and no sound).
On the phone I have given all permissions to kiwibrowser and the other apps send notifications (popup and sound).
In kiwibrowser I have given permission to everything regarding notifications, popups and sound, even to the single site notify.run.
Also tried cleaning data and reinstalling kiwibrowser several times.

I have created a new channel and the result does not change.
On the PC it works perfectly while on the phone it does not.
The weird thing is that it worked, then it stopped notifying.
Since it didn't work, I tried other browsers (Firefox / Chrome), but the result is the same.
I know more than to do.

On the pc (Linux Mint and Firefox / Chrome) everything works perfectly.
I can't understand where the mistake is.
Thanks a lot to those who help me.

**Comment by paulgb** [comment]
Hi @Contro28,

Sorry about this, there was a problem with my server setup that is now fixed. I've tested that it works for me in Kiwibrowser. Could you let me know if it works for you now or if you still have the issue?

Cheers

**Comment by Contro28** [comment]
Yes, notifications (popup and sound) seem to be working this morning.
Good job!
Thank you very much
