### ISSUE TITLE
Subscribed channel says: Not found

### ISSUE THREAD

**Issue by Contro28** [paulgb/notify.run#36]
Subscribed channel says: Not found.
Notifications (pop-ups and sounds) ok, but the channel doesn't show list and says (in red): Not found.
Phone and pc have the same problem.

Thank you very much.

**Comment by paulgb** [comment]
Sorry about that, I found the bug and am deploying a fix. Should be live in < 10 minutes.

**Comment by Contro28** [comment]
Working.

Tnx.
