### ISSUE TITLE
NameError: name 'raw_input' is not defined

### ISSUE THREAD

**Issue by sralloza** [paulgb/notify.run#7]
In the file cli.py, line 17, if python3 is being used, an exception will be raised, but instead of handling properly that exception, it raises another Exception.

To test it, install notify-run in python3, and execute "notify-run register" twice.

**Comment by paulgb** [comment]
Oh, that's no good :/ thanks for reporting! I'm planning to do another
release this weekend and will batch this in.

**Comment by paulgb** [comment]
Fixed in 0.0.11.
