### ISSUE TITLE
Error using info command

### ISSUE THREAD

**Issue by sralloza** [paulgb/notify.run#9]
When you use "notify-run info", an error is raised an captured. It displays "Expecting value: line 1 column 1 (char 0)". If you remove the except block in cli.py, lines 88-89, you can see that is a json.decoder.JSONDecodeError. It happens when trying to convert to json the 'info' version of the channel.

**Comment by paulgb** [comment]
Weird, can you paste the contents of `~/.config/notify-run`? (Feel free to change the endpoint URL to avoid making it public.)

**Comment by sralloza** [comment]
There you have:
{"endpoint": "https://notify.run/c/[channel-name]"}

**Comment by paulgb** [comment]
Strange, that looks right to me, I'm not sure why it's not decoding the JSON. Do the send and register commands work?

**Comment by sralloza** [comment]
As I saw, the problem is decoding the JSON from the request. I commented lines 88 and 89 from cli.py to see the error, and this is the output:

_C:\Users\srall>notify-run info
Traceback (most recent call last):
  File "c:\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "\_\_main\_\_", mod_spec)
  File "c:\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python\Python37\Scripts\notify-run.exe\__main__.py", line 9, in <module>
  File "c:\python\python37\lib\site-packages\notify_run\cli.py", line 85, in main
    func(notify, **args)
  File "c:\python\python37\lib\site-packages\notify_run\cli.py", line 29, in info
    print(notify.info())
  File "c:\python\python37\lib\site-packages\notify_run\__init__.py", line 116, in info
    r = requests.get(self.endpoint + '/info').json()
  File "c:\python\python37\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "c:\python\python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "c:\python\python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\python\python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)_

> Do the send and register commands work?
>
Now that you mention it, the register command works perfectly after the update, but the send command doesn't work. I don't think the problem is in the code, because no errors are raised (as far as I know), and I tried sending a message by myself using requests:
`requests.post("https://notify.run/c/[channel-name]", {'message': "message to send")`
And nothing happens, even in the channel url the message doesn't appear in the _"Recent messages"_ section.
However, if you use the curl command, it works perfectly.

I hope it helps :)

**Comment by sralloza** [comment]
Hey, I found the error. The endpoint configured was  "https://notify.run/c/[channel-name]", but it has to be  "https://notify.run/[channel-name]", without the "/c". 
So everything works fine, including the send command. 
Have you thought of using regex to check that the endpoint is correct when using the configure command?

**Comment by paulgb** [comment]
Ah, I see. I need to be more clear about the difference between the channel website URL (with the /c) and the POST endpoint (without the /c.) I'd love to make them the same URL for simplicity but they are actually served by different providers. Adding a regex to the register command is a good idea. For now I've added better error messages.
